# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: my_new_project # <-- Name of the project.
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  base_dbt_project:
    # Configuração padrão para todos os modelos dentro de base_dbt_project
    staging:
      +materialized: table
      +schema: staging
      +tags: stg
    analytics:
      +schema: analytics
      +tags: analytics
      +materialized: table
    sales:
      +schema: sales
      +tags: sales
      +materialized: table
    marts:
      +schema: marts
      +tags: marts
      +materialized: table
    elementary:
      +schema: elementary
      +tags: elementary
      +materialized: table
    re_data:
      +schema: re_data
      +tags: re_data
      +materialized: table
