# Nome do seu projeto DBT. Deve conter apenas caracteres minúsculos e sublinhados.
# Um bom nome de pacote deve refletir o nome da sua organização ou o uso pretendido desses modelos.
name: 'my_new_project'

# Versão do projeto
version: '1.0.0'

# Versão de configuração do DBT
config-version: 2

# Esta configuração especifica qual "perfil" o DBT usará para este projeto.
profile: 'default'

# Essas configurações especificam onde o DBT deve procurar diferentes tipos de arquivos.
# Você provavelmente não precisará alterar esses valores!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Diretório que armazenará os arquivos SQL compilados
target-path: "target"

# Diretórios a serem removidos pelo `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configurando modelos
# Documentação completa: https://docs.getdbt.com/docs/configuring-models

models:
  my_new_project:
    # Aplica-se a todos os arquivos em models/example/
    staging:
      +materialized: view
      +schema: stg

    marts: 
      +materialized: table
      +schema: marts

    fct_vendas:
      +materialized: table
      +schema: marts

seeds:
  my_new_project:
    sap_adventure_works: 
      +schema: sap_adw
