name: my_new_project
version: '1.0.0'

config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    base_dbt_project:
      staging:
        +materialized: table
        +schema: staging
        +tags: stg
      analytics:
        +schema: analytics
        +tags: analytics
        +materialized: table
      sales:
        +schema: sales
        +tags: sales
        +materialized: table
      marts:
        +schema: marts
        +tags: marts
        +materialized: table
      seeds:
        +schema: sap_adw
    +enabled: true
