version: 2

sources:
  - name: sap_adw
    schema: dbt_rpires
    tables:
      - name: address
      - name: countryregion
      - name: creditcard
      - name: customer
      - name: person
      - name: product
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: stateprovince
      - name: store
